name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make ForkTest
      run: |
        cd src/
        make _forktest
    - name: make kernel
      run: |
        cd src/
        make kernel
  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make kernel
      run: |
        cd src/
        make xv6.img

